name: Test Changelog Update

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_changelog:
    name: Test Changelog Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run changelog-from-release for all releases
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: "-l 6"
          commit: false
          push: false

      - name: Show the generated changelog
        run: |
          echo "### Generated CHANGELOG.md"
          cat CHANGELOG.md
